### ISSUE TITLE
python运行问题

### ISSUE THREAD

**Issue by jun-72** [OpenHUTB/carla_doc#31]
运行不了automatic_control_revised.py 显示缺少东西
![image](https://github.com/user-attachments/assets/49cb2fb5-7201-40cc-a2d2-5cae35bdf0c6)
C:\Users\ROG\anaconda3\python.exe F:/navigation/automatic_control_revised.py
INFO:  Found the required file in cache!  Carla/Maps/Nav/Town10HD_Opt.bin 
Traceback (most recent call last):
  File "F:/navigation/automatic_control_revised.py", line 61, in main
    vehicle = world.spawn_actor(ego_vehicle_bp, spawn_point)
RuntimeError: Spawn failed because of collision at spawn position

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/navigation/automatic_control_revised.py", line 161, in <module>
    main()
  File "F:/navigation/automatic_control_revised.py", line 156, in main
    vehicle.destroy()
UnboundLocalError: local variable 'vehicle' referenced before assignment

Process finished with exit code 1

**Comment by donghaiwang** [comment]
等着你来修复 ~

**Comment by donghaiwang** [comment]
需要提前湖南工商大学的地图：https://openhutb.github.io/carla_doc/core_map/
